<?php

namespace ContainerAytLKaU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SsEE8s6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ssEE8s6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ssEE8s6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\ChambreRepository', 'getChambreRepositoryService', true],
            'serviceRepo' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\ChambreRepository',
            'serviceRepo' => 'App\\Repository\\ServiceRepository',
        ]);
    }
}
