<?php

namespace ContainerLQbnq4a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0aAfb5wService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0aAfb5w' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0aAfb5w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rdvrepository' => ['privates', 'App\\Repository\\RendezVousRepository', 'getRendezVousRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\MedecinRepository', 'getMedecinRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'rdvrepository' => 'App\\Repository\\RendezVousRepository',
            'repository' => 'App\\Repository\\MedecinRepository',
            'security' => '?',
        ]);
    }
}
