<?php

namespace ContainerLQbnq4a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F2ZhAjhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F2ZhAjh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F2ZhAjh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::del' => ['privates', '.service_locator.QOjUGpS', 'get_ServiceLocator_QOjUGpSService', true],
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.QOjUGpS', 'get_ServiceLocator_QOjUGpSService', true],
            'App\\Controller\\BedListController::addChambre' => ['privates', '.service_locator.2djFsjl', 'get_ServiceLocator_2djFsjlService', true],
            'App\\Controller\\BedListController::delChambre' => ['privates', '.service_locator.Bofl8yD', 'get_ServiceLocator_Bofl8yDService', true],
            'App\\Controller\\BedListController::index' => ['privates', '.service_locator.ssEE8s6', 'get_ServiceLocator_SsEE8s6Service', true],
            'App\\Controller\\BedListController::modChambre' => ['privates', '.service_locator.N2UdB2i', 'get_ServiceLocator_N2UdB2iService', true],
            'App\\Controller\\BedListController::voirChambre' => ['privates', '.service_locator.396zBmr', 'get_ServiceLocator_396zBmrService', true],
            'App\\Controller\\MedecinController::index' => ['privates', '.service_locator.kh_CUhk', 'get_ServiceLocator_KhCUhkService', true],
            'App\\Controller\\MedecinController::rdvAdd' => ['privates', '.service_locator.0aAfb5w', 'get_ServiceLocator_0aAfb5wService', true],
            'App\\Controller\\MedecinListController::index' => ['privates', '.service_locator.kh_CUhk', 'get_ServiceLocator_KhCUhkService', true],
            'App\\Controller\\RDVListController::accept' => ['privates', '.service_locator.uRN7hil', 'get_ServiceLocator_URN7hilService', true],
            'App\\Controller\\RDVListController::decline' => ['privates', '.service_locator.uRN7hil', 'get_ServiceLocator_URN7hilService', true],
            'App\\Controller\\RDVListController::index' => ['privates', '.service_locator.uRN7hil', 'get_ServiceLocator_URN7hilService', true],
            'App\\Controller\\RDVListController::showAll' => ['privates', '.service_locator.uRN7hil', 'get_ServiceLocator_URN7hilService', true],
            'App\\Controller\\RegistrationController::registerAdmin' => ['privates', '.service_locator.W.VyWpL', 'get_ServiceLocator_W_VyWpLService', true],
            'App\\Controller\\RegistrationController::registerInfirmiere' => ['privates', '.service_locator.W.VyWpL', 'get_ServiceLocator_W_VyWpLService', true],
            'App\\Controller\\RegistrationController::registerPatient' => ['privates', '.service_locator.W.VyWpL', 'get_ServiceLocator_W_VyWpLService', true],
            'App\\Controller\\RegistrationController::registerSecretaire' => ['privates', '.service_locator.W.VyWpL', 'get_ServiceLocator_W_VyWpLService', true],
            'App\\Controller\\SecuriteController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\ServiceController::index' => ['privates', '.service_locator.v.nOAMI', 'get_ServiceLocator_V_NOAMIService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminController:del' => ['privates', '.service_locator.QOjUGpS', 'get_ServiceLocator_QOjUGpSService', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.QOjUGpS', 'get_ServiceLocator_QOjUGpSService', true],
            'App\\Controller\\BedListController:addChambre' => ['privates', '.service_locator.2djFsjl', 'get_ServiceLocator_2djFsjlService', true],
            'App\\Controller\\BedListController:delChambre' => ['privates', '.service_locator.Bofl8yD', 'get_ServiceLocator_Bofl8yDService', true],
            'App\\Controller\\BedListController:index' => ['privates', '.service_locator.ssEE8s6', 'get_ServiceLocator_SsEE8s6Service', true],
            'App\\Controller\\BedListController:modChambre' => ['privates', '.service_locator.N2UdB2i', 'get_ServiceLocator_N2UdB2iService', true],
            'App\\Controller\\BedListController:voirChambre' => ['privates', '.service_locator.396zBmr', 'get_ServiceLocator_396zBmrService', true],
            'App\\Controller\\MedecinController:index' => ['privates', '.service_locator.kh_CUhk', 'get_ServiceLocator_KhCUhkService', true],
            'App\\Controller\\MedecinController:rdvAdd' => ['privates', '.service_locator.0aAfb5w', 'get_ServiceLocator_0aAfb5wService', true],
            'App\\Controller\\MedecinListController:index' => ['privates', '.service_locator.kh_CUhk', 'get_ServiceLocator_KhCUhkService', true],
            'App\\Controller\\RDVListController:accept' => ['privates', '.service_locator.uRN7hil', 'get_ServiceLocator_URN7hilService', true],
            'App\\Controller\\RDVListController:decline' => ['privates', '.service_locator.uRN7hil', 'get_ServiceLocator_URN7hilService', true],
            'App\\Controller\\RDVListController:index' => ['privates', '.service_locator.uRN7hil', 'get_ServiceLocator_URN7hilService', true],
            'App\\Controller\\RDVListController:showAll' => ['privates', '.service_locator.uRN7hil', 'get_ServiceLocator_URN7hilService', true],
            'App\\Controller\\RegistrationController:registerAdmin' => ['privates', '.service_locator.W.VyWpL', 'get_ServiceLocator_W_VyWpLService', true],
            'App\\Controller\\RegistrationController:registerInfirmiere' => ['privates', '.service_locator.W.VyWpL', 'get_ServiceLocator_W_VyWpLService', true],
            'App\\Controller\\RegistrationController:registerPatient' => ['privates', '.service_locator.W.VyWpL', 'get_ServiceLocator_W_VyWpLService', true],
            'App\\Controller\\RegistrationController:registerSecretaire' => ['privates', '.service_locator.W.VyWpL', 'get_ServiceLocator_W_VyWpLService', true],
            'App\\Controller\\SecuriteController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\ServiceController:index' => ['privates', '.service_locator.v.nOAMI', 'get_ServiceLocator_V_NOAMIService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminController::del' => '?',
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\BedListController::addChambre' => '?',
            'App\\Controller\\BedListController::delChambre' => '?',
            'App\\Controller\\BedListController::index' => '?',
            'App\\Controller\\BedListController::modChambre' => '?',
            'App\\Controller\\BedListController::voirChambre' => '?',
            'App\\Controller\\MedecinController::index' => '?',
            'App\\Controller\\MedecinController::rdvAdd' => '?',
            'App\\Controller\\MedecinListController::index' => '?',
            'App\\Controller\\RDVListController::accept' => '?',
            'App\\Controller\\RDVListController::decline' => '?',
            'App\\Controller\\RDVListController::index' => '?',
            'App\\Controller\\RDVListController::showAll' => '?',
            'App\\Controller\\RegistrationController::registerAdmin' => '?',
            'App\\Controller\\RegistrationController::registerInfirmiere' => '?',
            'App\\Controller\\RegistrationController::registerPatient' => '?',
            'App\\Controller\\RegistrationController::registerSecretaire' => '?',
            'App\\Controller\\SecuriteController::login' => '?',
            'App\\Controller\\ServiceController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:del' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\BedListController:addChambre' => '?',
            'App\\Controller\\BedListController:delChambre' => '?',
            'App\\Controller\\BedListController:index' => '?',
            'App\\Controller\\BedListController:modChambre' => '?',
            'App\\Controller\\BedListController:voirChambre' => '?',
            'App\\Controller\\MedecinController:index' => '?',
            'App\\Controller\\MedecinController:rdvAdd' => '?',
            'App\\Controller\\MedecinListController:index' => '?',
            'App\\Controller\\RDVListController:accept' => '?',
            'App\\Controller\\RDVListController:decline' => '?',
            'App\\Controller\\RDVListController:index' => '?',
            'App\\Controller\\RDVListController:showAll' => '?',
            'App\\Controller\\RegistrationController:registerAdmin' => '?',
            'App\\Controller\\RegistrationController:registerInfirmiere' => '?',
            'App\\Controller\\RegistrationController:registerPatient' => '?',
            'App\\Controller\\RegistrationController:registerSecretaire' => '?',
            'App\\Controller\\SecuriteController:login' => '?',
            'App\\Controller\\ServiceController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
