<?php

namespace ContainerLQbnq4a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N2UdB2iService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N2UdB2i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N2UdB2i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chambre' => ['privates', '.errored..service_locator.N2UdB2i.App\\Entity\\Chambre', NULL, 'Cannot autowire service ".service_locator.N2UdB2i": it references class "App\\Entity\\Chambre" but no such service exists.'],
            'repository' => ['privates', 'App\\Repository\\ChambreRepository', 'getChambreRepositoryService', true],
        ], [
            'chambre' => 'App\\Entity\\Chambre',
            'repository' => 'App\\Repository\\ChambreRepository',
        ]);
    }
}
