<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSG7dFqs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSG7dFqs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSG7dFqs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSG7dFqs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSG7dFqs\App_KernelDevDebugContainer([
    'container.build_hash' => 'SG7dFqs',
    'container.build_id' => 'a5f8836b',
    'container.build_time' => 1615289544,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSG7dFqs');
