<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHRbZQaX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHRbZQaX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHRbZQaX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHRbZQaX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHRbZQaX\App_KernelDevDebugContainer([
    'container.build_hash' => 'HRbZQaX',
    'container.build_id' => '2aadf628',
    'container.build_time' => 1615566015,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHRbZQaX');
