<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLQbnq4a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLQbnq4a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLQbnq4a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLQbnq4a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLQbnq4a\App_KernelDevDebugContainer([
    'container.build_hash' => 'LQbnq4a',
    'container.build_id' => '0533e555',
    'container.build_time' => 1613938994,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLQbnq4a');
